[package]
name = "proofs-args-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-std = "0.4.0"
ndarray = "0.16.1"

[dev-dependencies]
ark-test-curves = {version = "0.4.2", features = ["bls12_381_scalar_field"] }
